### ISSUE TITLE
application of the design

### ISSUE THREAD

**Issue by Regiss05** [Benmuiruri/stream-it-capstone#31]
- Implement your popup design to improve the accessibility of the website to different users
- The website is not responsive; please make it so that it adapts to different device screens.

**Comment by Benmuiruri** [comment]
Thanks for raising the issue. I will be working on this today. I will link the PR here when I make the changes. Thanks

**Comment by Benmuiruri** [comment]
#33 Fixes the above issues. Thanks for pointing them out.
