### ISSUE TITLE
Project review: 04.16.22.

### ISSUE THREAD

**Issue by virag-ky** [Benmuiruri/stream-it-capstone#37]
## HTML/CSS/JavaScript
* the code is looking clean in all of the files
* I see you are using ES6 syntax throughout the code which is great
* the video description is great, you guys explained everything important
* the Readme file is descriptive enough

## Suggestions:
* on the mobile view you could make certain containers wider so that they don't look too narrow on the screen

### Overall the project looks great, works as it should, I like the colors, so basically I don't have anything negative to say. You guys did really well! :+1: :100:

**Comment by Benmuiruri** [comment]
Thanks @virag-ky for the review. 

Our mobile view is not great because we did not start with a mobile-first approach. This project really taught us the importance of a mobile-first approach.

**Comment by Benmuiruri** [comment]
I updated the mobile view styles, it should look better now :). 

Issue addressed with this PR  #38
